pipeline {
    agent any

    environment {
        VAULT_PASSWORD_FILE = "vault_pass.txt"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/mait002/Book-Recommender.git'
            }
        }

        stage('Install Ansible') {
            steps {
                sh '''
                    sudo apt-get update
                    sudo apt-get install -y ansible
                '''
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                sh '''
                    ansible-playbook ansible/playbook.yml \
                        -i ansible/hosts.ini \
                        --vault-password-file $VAULT_PASSWORD_FILE
                '''
            }
        }
    }
}
