pipeline {

    agent any

    environment {
        VAULT_PASS = credentials('vault-pass')
    }
    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/mait002/Book-Recommender.git'
            }
        }

        stage('Install Ansible') {
            steps {
                sh 'sudo apt-get update && sudo apt-get install -y ansible'
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                //write vault password to temp file
                writeFile file: 'vault_pass.txt', text: "${env.VAULT_PASS}"

                // Run Ansible playbook using the vault password file
                sh '''
                    ansible-playbook -i ansible/hosts.ini ansible/playbook.yml \
                    --vault-password-file vault_pass.txt
                '''
            }
        }
    }

    post {
        cleanup {
            sh 'rm -f vault_pass.txt'
        }
    }

}

